describe('Create Account', () => {
  beforeEach(() => {
    cy.visit('')
    cy.login()
  })
  /*EDIT ACCOUNT */
  it('Edit empty name - Failed', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#firstname').clear()
    cy.get('#lastname').clear()
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.url().should('include','account')
    cy.get('#firstname-error').should('contain.text','This is a required field.')
    cy.get('#lastname-error').should('contain.text','This is a required field.')
  })
  it('Edit name & empty email - Failed', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#change-email').click()
    cy.get('#firstname').clear().type('Octaviane')
    cy.get('#lastname').clear().type('Yolanda')
    cy.get('#email').clear()
    cy.get('#current-password').type('Viane1234.')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('#email-error').should('contain.text','This is a required field.')
  })

  it('Edit name & empty password - Failed', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#change-password').click()
    cy.get('#firstname').clear().type('Octaviane')
    cy.get('#lastname').clear().type('Yolanda')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.get('#current-password-error').should('contain.text','This is a required field.')
    cy.get('#password-error').should('contain.text','This is a required field.')
    cy.get('#password-confirmation-error').should('contain.text','This is a required field.')

  })

  it('Edit Name - Success', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#firstname').clear().type('Octaviane')
    cy.get('#lastname').clear().type('Yolanda')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.url().should('include','account')
    cy.get('.message-success').should('contain.text','You saved the account information.')
  })
  it('Edit name & email - Success', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#change-email').click()
    cy.get('#firstname').clear().type('Octaviane')
    cy.get('#lastname').clear().type('Yolanda')
    cy.get('#email').clear().type('viane@gmail.com')
    cy.get('#current-password').type('Viane1234.')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.url().should('include','account')
    cy.get('.message-success').should('contain.text','You saved the account information.')
  })

  it('Edit name & password - Success', () => {
    cy.wait(9000)
    cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
    cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
    cy.get('.block-dashboard-info > .block-content > .box > .box-actions > .edit > span').click()
    cy.url().should('include','edit')
    cy.get('#change-password').click()
    cy.get('#firstname').clear().type('Octaviane')
    cy.get('#lastname').clear().type('Yolanda')
    cy.get('#current-password').type('Viane1234.')
    cy.get('#password').type('Viane1234.')
    cy.get('#password-confirmation').type('Viane1234.')
    cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
    cy.url().should('include','account')
    cy.get('.message-success').should('contain.text','You saved the account information.')
  })


/*EDIT ADDRESS */
it('add Address - Failed', () => {
  cy.wait(5000)
  cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  cy.get('.block-title > .action > span').click()
  cy.url().should('include','address')
  cy.get('#company').type('Private')
  cy.get('#region_id').select('Alaska')
  cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  cy.wait(1000)
  cy.get('#telephone-error').should('contain.text','This is a required field.')
  cy.get('#street_1-error').should('contain.text','This is a required field.')
  cy.get('#city-error').should('contain.text','This is a required field.')
  cy.get('#zip-error').should('contain.text','This is a required field.')
})

it('add Address - Success', () => {
  cy.wait(5000)
  cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  cy.get('.block-title > .action > span').click()
  cy.url().should('include','address')
  cy.get('#company').type('Private')
  cy.get('#telephone').type('817235123126312')
  cy.get('#street_1').type('setia')
  cy.get('#street_2').type('budi')
  cy.get('#street_3').type('Bandung')
  cy.get('#city').type('Jakarta')
  cy.get('#region_id').select('Alaska')
  cy.get('#zip').type('99608')
  cy.get('#country').select('Indonesia')
  cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  cy.get('.message-success').should('contain.text','You saved the address.')
})

it.only('Edit Address - Failed', () => {
  cy.wait(5000)
  cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  cy.get('.block-title > .action > span').click()
  cy.url().should('include','address')
  cy.wait(1000)
  cy.get('.column > .actions-toolbar > div.primary > .action').click()
  cy.get('#company').type('Private')
  cy.get('#region_id').select('Alaska')
  cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  cy.wait(1000)
  cy.get('#telephone-error').should('contain.text','This is a required field.')
  cy.get('#street_1-error').should('contain.text','This is a required field.')
  cy.get('#city-error').should('contain.text','This is a required field.')
  cy.get('#zip-error').should('contain.text','This is a required field.')
})

it('edit Address - Success', () => {
  cy.wait(5000)
  cy.get(':nth-child(2) > .customer-welcome > .customer-name > .action').click()
  cy.get(':nth-child(2) > .customer-welcome > .customer-menu > .header > :nth-child(1) > a').click()
  cy.get('.block-title > .action > span').click()
  cy.url().should('include','address')
  cy.wait(1000)
  cy.get('.column > .actions-toolbar > div.primary > .action').click()
  cy.get('#company').type('Private')
  cy.get('#telephone').type('817235123126312')
  cy.get('#street_1').type('setia')
  cy.get('#street_2').type('budi')
  cy.get('#street_3').type('Bandung')
  cy.get('#city').type('Jakarta')
  cy.get('#region_id').select('Alaska')
  cy.get('#zip').type('99608')
  cy.get('#country').select('Indonesia')
  cy.get('#form-validate > .actions-toolbar > div.primary > .action').click()
  cy.get('.message-success').should('contain.text','You saved the address.')
})
})